#ifndef RETROLINK_BOARD_CONFIG_H
#define RETROLINK_BOARD_CONFIG_H

#include <stdint.h>

#define RETROLINK_SPEC_VERSION "1.00"

#ifndef RETROLINK_FW_VERSION
#define RETROLINK_FW_VERSION "1.00"
#endif

#ifndef RETROLINK_HW_REVISION
#define RETROLINK_HW_REVISION "1.00"
#endif

#define RETROLINK_USB_HOST_DP_GPIO 2u
#define RETROLINK_USB_HOST_DM_GPIO 3u

#define RETROLINK_USB_VBUS_EN_GPIO 4u
#define RETROLINK_USB_VBUS_FAULT_GPIO 5u

#define RETROLINK_MSX_UP_GPIO 6u
#define RETROLINK_MSX_DOWN_GPIO 7u
#define RETROLINK_MSX_LEFT_GPIO 8u
#define RETROLINK_MSX_RIGHT_GPIO 9u
#define RETROLINK_MSX_TRIGGER_A_GPIO 10u
#define RETROLINK_MSX_TRIGGER_B_GPIO 11u
#define RETROLINK_MSX_OUT_STROBE_GPIO 12u
#define RETROLINK_MSX_5V_SENSE_GPIO 13u

#define RETROLINK_STATUS_LED_GPIO 16u
#define RETROLINK_STATUS_LED_PULSE_MS 80u

#define RETROLINK_SYS_CLOCK_KHZ 120000u

#define RETROLINK_DEBUG_CDC_HEARTBEAT_MS 2000u

#endif