#ifndef RETROLINK_BOARD_CONFIG_H
#define RETROLINK_BOARD_CONFIG_H

#define RETROLINK_HW_REVISION "1.00"

#define RETROLINK_MD_UP_GPIO 28u
#define RETROLINK_MD_BA_GPIO 27u
#define RETROLINK_MD_DOWN_GPIO 26u
#define RETROLINK_MD_THSEL_GPIO 15u
#define RETROLINK_MD_LEFT_GPIO 14u
#define RETROLINK_MD_CSTART_GPIO 13u
#define RETROLINK_MD_RIGHT_GPIO 12u

#define RETROLINK_MSX_UP_GPIO 0u
#define RETROLINK_MSX_TRIGGER_A_GPIO 1u
#define RETROLINK_MSX_DOWN_GPIO 2u
#define RETROLINK_MSX_TRIGGER_B_GPIO 3u
#define RETROLINK_MSX_LEFT_GPIO 4u
#define RETROLINK_MSX_OUT_STROBE_GPIO 5u
#define RETROLINK_MSX_RIGHT_GPIO 6u

#define RETROLINK_STATUS_LED_GPIO 16u
#define RETROLINK_STATUS_LED_PULSE_MS 80u

#define RETROLINK_MD_SETTLE_US 10u
#define RETROLINK_MD_RESET_US 3000u
#define RETROLINK_MD_MAX_FRAME_US 500u
#define RETROLINK_MD_POLL_US 5000u

#endif
